export const demoTeam = [
  {
    id: 1,
    profile: "/dev-league-team/abdulqawi-laniyan.jpg",
    name: "AbdulQawi Laniyan Dotun",
    role: "Community Founder & Lead",
    description:
      "Former co-founder of Opendoor. Early staff at Spotify and Clearbit.",
    linkedin:
      "https://www.linkedin.com/in/abdul-qawi-laniyan-173355248?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    twitter: "https://x.com/Devdotun?t=fBZqZAT8Jwp_hXECNQzmJQ&s=09",
    github: "https://github.com/Oladotunlaniyan",
  },
  {
    id: 2,
    profile: "/dev-league-team/quadri.jpg",
    name: "Abiola Azeez Quadri",
    role: "Management Lead (Community Co-Lead)",
    description: "Lead engineering teams at Kuda, Opay, and Protocol Labs.",
    linkedin:
      "https://www.linkedin.com/in/abiola-azeez-688865201?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    twitter: "https://twitter.com/darnyy_abiola?t=korP_twbt4zomd6q8LD6HQ&s=09",
    github: "https://github.com/Azeez-Abiola",
  },
  //  {
  //     id: 3,
  //     profile: "/dev-league-team/abdullah-tijani.jpg",
  //     name: "Abdullah Tijani",
  //     role: "Dev League Technical Lead ",
  //     description: "Former PM for Bamboohr, Lambda School, and On Deck.",
  //     linkedin: "https://www.linkedin.com/in/TheYoungestDev",
  //     twitter: "https://twitter.com/abdull_network",
  //     github: "https://github.com/TheYoungestDev"
  // },
  {
    id: 4,
    profile: "/dev-league-team/bello-lateefat.jpg",
    name: "Bello Lateefat",
    role: "Social Media Manager & (Content Co-Lead) ",
    description: "Former frontend dev for Coinbase, and CryptoKnight.",
    linkedin:
      "https://www.linkedin.com/in/teefah-bello-17a961273?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    twitter: "https://x.com/Teefah_codes?t=YnbS6P0bOJfVPGk8pa0fRA&s=09",
    github: "https://github.com/Tobylobah",
  },
  {
    id: 5,
    profile: "/dev-league-team/confidence-ufuoma.jpg",
    name: "Confidence Ufuoma",
    role: "Community Engagement Manager",
    description: "Lead backend dev at Clearbit. Former Clearbit and Loom.",
    linkedin: "https://www.linkedin.com/in/confidence-ufuoma-frontenddeveloper",
    twitter: "https://x.com/plantcodess",
    github: "https://github.com/Plantcodess",
  },
  {
    id: 6,
    profile: "/dev-league-team/kabir-yusuf.jpg",
    name: "Kabir Yusuf",
    role: "Design Lead",
    description:
      "Founding design team at Figma. Former Pleo, Stripe, and Tile.",
    linkedin:
      "https://www.linkedin.com/in/abdulkabir-yusuf-a614b42a7?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    twitter: "https://x.com/kabiryusuf24",
    behance: "https://www.behance.net/abdulkabiryusuf1",
  },
  // {
  //     id: 7,
  //     profile: "/dev-league-team/ayoola-israel.jpg",
  //     name: "Ayoola Israel Muyiwa",
  //     role: "Dev League Content Writer",
  //     description: "Lead user research for Slack. Contractor for Netflix and Udacity.",
  //     linkedin: "https://www.linkedin.com/in/israel-ayoola-7a88b4298?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  //     twitter: "https://twitter.com/Indomie_Boy?t=XGCRW6bkU6brNT7qWAxshA&s=09",
  // },
  {
    id: 8,
    profile: "/dev-league-team/emmanuel-ige.jpg",
    name: "Emmanuel Ige",
    role: "Design Co-Lead",
    description: "Lead CX at Wealthsimple. Former PagerDuty and Sqreen.",
    linkedin:
      "https://www.linkedin.com/in/emmanuel-ige-861a01253?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    twitter: "https://x.com/_akande1?t=NNlpCmHzdppnm55JdWISNg&s=09",
  },
  //  {
  //     id: 9,
  //     profile: "/dev-league-team/alabi-abdullah.jpg",
  //     name: "Alabi Abdullah Ayodeji",
  //     role: "Dev League Content Writer",
  //     description: "Lead CX at Wealthsimple. Former PagerDuty and Sqreen.",
  //     linkedin: "https://www.linkedin.com/in/alabi-abdullahi-7a313523a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  //     twitter: "https://x.com/Alabiabdullah1",
  //     github: "https://github.com/Alabiabdullah1"
  // },
  // {
  //     id: 10,
  //     profile: "/dev-league-team/aliu-aminat.jpg",
  //     name: "Aliu Aminat",
  //     role: "Dev League Co-Creative Director",
  //     description: "Lead CX at Wealthsimple. Former PagerDuty and Sqreen.",
  //     linkedin: "https://www.linkedin.com/in/aminat-aliu-993a83229",
  //     twitter: "https://x.com/aminatdamilola5",
  // },
  {
    id: 11,
    profile: "/dev-league-team/mob-codes.jpg",
    name: "Boluwade Folarin",
    role: "Technical Lead",
    description: "Lead CX at Wealthsimple. Former PagerDuty and Sqreen.",
    linkedin: "https://www.linkedin.com/in/boluwade-folarin",
    twitter: "https://x.com/moboluwade_",
    github: "https://github.com/moboluwade",
  },
  {
    id: 12,
    profile: "/dev-league-team/ibrahim.jpg",
    name: "Ibrahim Abdulazeez",
    role: "Content Lead",
    description: "Lead CX at Wealthsimple. Former PagerDuty and Sqreen.",
    linkedin: "https://www.linkedin.com/in/ibrahim-abdulazeez-74ab76297",
    twitter: "https://x.com/metacienfuegos",
  },
];
