export const demoTeam = [
    {
        id: 1,
        profile: "/demo-team/photo-1.png",
        name: "Qawi",
        role: "Founder & Developer",
        description: "Former co-founder of Opendoor. Early staff at Spotify and Clearbit.",
        devBoolean: true,
        designerBoolean: false,
    }, {
        id: 2,
        profile: "/demo-team/photo-2.png",
        name: "Habeeb Lawal",
        role: "Engineering Manager",
        description: "Lead engineering teams at Kuda, Opay, and Protocol Labs.",
        devBoolean: false,
        designerBoolean: true,
    }, {
        id: 3,
        profile: "/demo-team/photo-3.png",
        name: "Lara Steiner",
        role: "Product Manager",
        description: "Former PM for Bamboohr, Lambda School, and On Deck.",
        devBoolean: true,
        designerBoolean: false,
    }, {
        id: 4,
        profile: "/demo-team/photo-4.png",
        name: "Demi Wilkinson",
        role: "Frontend Developer",
        description: "Former frontend dev for Coinbase, and CryptoKnight.",
        devBoolean: false,
        designerBoolean: true,
    }, {
        id: 5,
        profile: "/demo-team/photo-5.png",
        name: "Candice Wu",
        role: "Backend Developer",
        description: "Lead backend dev at Clearbit. Former Clearbit and Loom.",
        devBoolean: true,
        designerBoolean: false,
    }, {
        id: 6,
        profile: "/demo-team/photo-6.png",
        name: "Natali Craig",
        role: "Product Designer",
        description: "Founding design team at Figma. Former Pleo, Stripe, and Tile.",
        devBoolean: false,
        designerBoolean: true,
    }, {
        id: 7,
        profile: "/demo-team/photo-5.png",
        name: "Drew Cano",
        role: "UX Researcher",
        description: "Lead user research for Slack. Contractor for Netflix and Udacity.",
        devBoolean: true,
        designerBoolean: false,
    }, {
        id: 8,
        profile: "/demo-team/photo-3.png",
        name: "Orlando Diggs",
        role: "Customer Success",
        description: "Lead CX at Wealthsimple. Former PagerDuty and Sqreen.",
        devBoolean: false,
        designerBoolean: true,
    },
]