export const eventsCard = [
  {
    id: 1,
    day: '18',
    month: 'dec',
    title: 'Why Techies Need Law',
    content: ' How do you create compelling presentations......',
    type: 'Published',
    date: 'Jan 16, 2024',
  },
  {
    id: 2,
    day: '18',
    month: 'dec',
    title: 'Why Techies Need Law',
    content: ' How do you create compelling presentations......',
    type: 'Published',
    date: 'Jan 16, 2024',
  },
  {
    id: 3,
    day: '18',
    month: 'dec',
    title: 'Why Techies Need Law',
    content: ' How do you create compelling presentations......',
    type: 'Published',
    date: 'Jan 16, 2024',
  },
  {
    id: 4,
    day: '18',
    month: 'dec',
    title: 'Why Techies Need Law',
    content: ' How do you create compelling presentations......',
    type: 'Published',
    date: 'Jan 16, 2024',
  },
  {
    id: 5,
    day: '18',
    month: 'dec',
    title: 'Why Techies Need Law',
    content: ' How do you create compelling presentations......',
    type: 'Published',
    date: 'Jan 16, 2024',
  },
  {
    id: 6,
    day: '18',
    month: 'dec',
    title: 'Why Techies Need Law',
    content: ' How do you create compelling presentations......',
    type: 'Published',
    date: 'Jan 16, 2024',
  },
]
